[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c93e9ee742ef334a1a6c012092107fc76e560a16"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "c41da8b6277f0f985d90278281afef2b9b303a7b5cceacfe7df4897048d27846"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v11.0.0+0/SPIRV_LLVM_Translator.v11.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7dd3528a90fc64aa3cd2c0fc3b5c37ad164ffce6"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "5a85186897ba839569de2dc28638d6d620876d12bd043d45bc472b3573ab89ab"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v11.0.0+0/SPIRV_LLVM_Translator.v11.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "11c82db5e508e960c8ff9a7ef4d1d8e403fe8e2a"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "1cd270b20b28ff668598d334b787f3361b2a31915513b83fcc262252527f4e58"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v11.0.0+0/SPIRV_LLVM_Translator.v11.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "27694e62f4080c4be1c36a5e2b216f5079e3f03a"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "a8359dcb7823e3afbd0a6e3ce7f6ba7c32f10866ac0cacdb6eb223c88b09bfd0"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v11.0.0+0/SPIRV_LLVM_Translator.v11.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2e8acd0346d852147ef778336ca85daad162517d"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "b03aa2135fd0671f749be826568b4110615a6b15ae9beda3e3814e8b72e0d7a9"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v11.0.0+0/SPIRV_LLVM_Translator.v11.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af4354f29d9e4b5124cfa3b9461ce476517b987b"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "881e4f66cc90aafbc6160cb56ec0fa5949efda76937acf11fea264e108397d5c"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v11.0.0+0/SPIRV_LLVM_Translator.v11.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "359e8dff2752e4d58bf1ff7854c69d6ca5f25b42"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "4bf2a1efb29d0451a65ce0760e4698a417a33258e9027fba33d5b4f6ef397d5e"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v11.0.0+0/SPIRV_LLVM_Translator.v11.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "033fadf2a2d991520ee559ea829c75cf28979d4a"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "200bd37ff5ef7a912a26bc9908c5796e14cc93c7583698124584be1bf125a323"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v11.0.0+0/SPIRV_LLVM_Translator.v11.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c4a79ee4a5ff9852d8ee2f7f6d3b198fccb8ef05"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "deb4d19de94830ef2b86aa0fc3399d6fc7baf06dc4b8ee077e0646a775636f77"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v11.0.0+0/SPIRV_LLVM_Translator.v11.0.0.i686-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf62900f3d48d1a4abe20b34859ab6aca0ae064e"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "2c6810dd41d86be928680f210d0b7195dd6b86b122f9e11ad9ef1380b5e14a5b"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v11.0.0+0/SPIRV_LLVM_Translator.v11.0.0.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cdb8ee855a6151f319328e8c4cc2348a32f61f54"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "d6f63d7be1c615bbaf09e6254766ea24f6c4c1a3a70be47dec17c7216c518607"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v11.0.0+0/SPIRV_LLVM_Translator.v11.0.0.i686-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6eea7fa9e0b86c6f166c4cca7e340633c9f4c8b"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "ec57aba76d122afdc951e024176005c45387d606d40f75e0df33781916c6d419"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v11.0.0+0/SPIRV_LLVM_Translator.v11.0.0.i686-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4c45338e92d85dfd3fd985c24d7329c484b81b31"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "7b883001eb3f0eaded0e6369af3f10af4185b17a93b0c731cb5525c70497b900"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v11.0.0+0/SPIRV_LLVM_Translator.v11.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d685f77fb8c42a56e95eabbd26ddc06f230f5cc5"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "368528cc39ecc9c1e541f7894894f4a366db09ec98cea538cb40169e3c48ea4f"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v11.0.0+0/SPIRV_LLVM_Translator.v11.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "907dac3f656657f96e3728e55bc77e4dc2943703"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "7567672d44bf63d8fdac13b88cdee2a4d57041cf76bd90d402e862d9303ee6fa"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v11.0.0+0/SPIRV_LLVM_Translator.v11.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca3afe83cfea487b1059061e1eadab8c4fc02a48"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "dc9aec0dea7b03d6892c1852c06297a8c1239815550d9e72d2d07c301f4debf5"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v11.0.0+0/SPIRV_LLVM_Translator.v11.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
git-tree-sha1 = "861fad664ece24d1ecd38aed5b74c45972c3d081"
os = "macos"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "781776a207032cb88fd17ab56316ba8f0ba567ab7bc73a0fee825e9642e85542"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v11.0.0+0/SPIRV_LLVM_Translator.v11.0.0.x86_64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cbcc2295bbb8eb0f114ab6bcd01af20dfbd093b3"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "1883f71dff369f375aedf31053a7f07134ac8d3edc557ffda331445ace7c9ef9"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v11.0.0+0/SPIRV_LLVM_Translator.v11.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b8eee876798647a36b9b4469b239b2b34ae1880"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "a7afc56b5f8eb1a8a0b340b01097a806a53946b9faaf7139c46263f87cf32d57"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v11.0.0+0/SPIRV_LLVM_Translator.v11.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6ea95091f51de876845026acd3a77a9402acd750"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "dcb07d50362a93a9389780e0fd094a9aa7a50033945a2af5624280f44b0a3c4e"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v11.0.0+0/SPIRV_LLVM_Translator.v11.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ca31f51ac0f32f352ac8b3935879afee17e8df8"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "326f78c45b39313e375a3e429fb0d1753bf054e2c65036cc4dffd9efe345db41"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v11.0.0+0/SPIRV_LLVM_Translator.v11.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
git-tree-sha1 = "271caf541ef67bbcac916a0ba2f03a2bedabe297"
os = "freebsd"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "e0c157e24a3fcd327dd958e30195e9eec7876cc6802a6fced4eac1ab5fb34b96"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v11.0.0+0/SPIRV_LLVM_Translator.v11.0.0.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a6d2ee200abea3213f1b4718bf8bbe1aeea78769"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "a93668a83ec11717905affb13c58a733f74eadca68b9f8db1756daf7188c2510"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v11.0.0+0/SPIRV_LLVM_Translator.v11.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "76fbf593479a17ebc4133b927b736bb18206740e"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "10a6ed55b9ae5042384547a4162517b991dfdf470dc3422fc90e78bd8bc6fca0"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v11.0.0+0/SPIRV_LLVM_Translator.v11.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
